### ISSUE TITLE
how to combine the Robotiq-140 gripper with the Moveit Rviz.

### ISSUE THREAD

**Issue by xs-alt** [beta-robots/robotiq#7]
Hi carlosjoserg,
  Today, we get our Robotiq_140 gripper and we have successfully use the CModelRtuNode and CModelSimpleController to controll the gripper via our PC thought USB. While we want to do much more than that, now we would like to combine the gripper with Moveit Rivz through ROS,
![rviz](https://user-images.githubusercontent.com/24916161/38795588-5dcefc66-418b-11e8-9e0a-f7086a5fe57d.png)
![finger](https://user-images.githubusercontent.com/24916161/38795594-604de718-418b-11e8-9066-971c4c9c92d3.png)
Well, first we cannot execute the gripper plan in Rviz because of lacking controller. Second, if we use the  CModelSimpleController to control the gripper we cannot see the change in Rviz .
Previously, we combine the UR10 with Rviz successfully using the ur_modern_driver package , that is if we plan UR in Rviz and execute the plan, the real UR will follow the action. 
We just would like the gripper to do the same thing as the UR, could you help us since we are all new to the gripper.

**Comment by carlosjoserg** [comment]
Hi @AlexWang1996 

Hardly you will get MoveIt! connection if you use the CModelSimpleController: You'd need a ros-controls based controller.

I've been using the [position_controllers/GripperActionController](https://github.com/ros-controls/ros_controllers/tree/kinetic-devel/gripper_action_controller) in combination with our implementation of [hardware interface](https://github.com/beta-robots/robotiq/tree/new_2_finger_models/robotiq_2f_hw_usb).

I don't really know whether MoveIt! has an interface for this controller type, I have only used via the JointTrajectoryController.. though this kind does not work well with the gripper using the USB interface.

If you want to have actually coordinated motions of UR + Gripper, that's a different story, you might need to convert both hardware interfaces to [combined hardware interfaces](https://github.com/ros-controls/ros_control/tree/melodic-devel/combined_robot_hw).

**Comment by xs-alt** [comment]
Thank you for your reply! @carlosjoserg 
It's really challenging for me since l am new to the ROS too ... 
em... l notice that there is a bringup.launch within this repo and wonder whether we can utilize it or not ?

**Comment by philwall3** [comment]
Maybe this will help you: https://github.com/philwall3/UR5-with-Robotiq-Gripper-and-Kinect

**Comment by xs-alt** [comment]
@philwall3  Really thank you. l will follow it!

**Comment by xs-alt** [comment]
Again, thank you for all of your help. l have solved this problem with your help. So l come to close the issue.
